<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR">
    <context>
        <name>behavior_1/behavior.xar:/Animated Say</name>
        <message>
            <source>Hello</source>
            <comment>Text</comment>
            <translation type="obsolete">Hello</translation>
        </message>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="vanished">Bonjour</translation>
        </message>
        <message>
            <source>Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</source>
            <comment>Text</comment>
            <translation type="obsolete">Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Animated Say (1)</name>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="vanished">Bonjour</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Association des anciens</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Les étudiants diplômés de l'IMÉRIR, constituent un grand réseau professionel, concrétisé sous la forme d'une association loi de 1901, nommé &quot;Alumni IMÉRIR&quot;. &quot;Alumni&quot;, signifie &quot;anciens élèves&quot;, en anglais. Créée en 1994, cette association, a pour tâche de maintenir le liens, entre tous les diplômés. Elle mène des actions, vers les diplômés de l'école, vers les imériens, vers les entreprises partenaires, et vers les cabinets de recrutement. &quot;Alumni IMÉRIR&quot; dispose, également, d'une adresse email, d'un numéro de téléphone, d'une page Facebook, d'une page Line keuh dine, et d'une boutique en ligne. Wahou ! Aujourd'hui, le réseau des anciens étudiants de l'IMÉRIR, comporte 1300 membres, répartis, dans tous les secteurs économiques (banques, assurances, santé, recherche, enseignement, sociétés de service informatique...). Vraiment ! Comme c'est top !</source>
            <comment>Text</comment>
            <translation type="unfinished">Les étudiants diplômés de l'IMÉRIR, constituent un grand réseau professionel, concrétisé sous la forme d'une association loi de 1901, nommé &quot;Alumni IMÉRIR&quot;. &quot;Alumni&quot;, signifie &quot;anciens élèves&quot;, en anglais. Créée en 1994, cette association, a pour tâche de maintenir le liens, entre tous les diplômés. Elle mène des actions, vers les diplômés de l'école, vers les imériens, vers les entreprises partenaires, et vers les cabinets de recrutement. &quot;Alumni IMÉRIR&quot; dispose, également, d'une adresse email, d'un numéro de téléphone, d'une page Facebook, d'une page Line keuh dine, et d'une boutique en ligne. Wahou ! Aujourd'hui, le réseau des anciens étudiants de l'IMÉRIR, comporte 1300 membres, répartis, dans tous les secteurs économiques (banques, assurances, santé, recherche, enseignement, sociétés de service informatique...). Vraiment ! Comme c'est top !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Erasmus</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Les imériens étudiants dans la formation &quot;Manager de systèmes informatique et robotique&quot; peuvent partir à l’étranger, dans le cadre du programme Erasmus. Plongés dans cette expérience unique et inoubliable, ils continuent d'étudier, mais dans une université ou une école d’accueil, tout en perfectionnant leur anglais, en découvrant de nouveaux pays, ainsi que de nouvelles cultures, tout en nouant de nouvelles relations. Quelle chance ! Non ? L’IMÉRIR est partenaire de plusieurs écoles et universités dans toute l’Europe, et avec lequel de riches échanges se font. Par exemple, il y a l’université des sciences appliquées de Laponie en Finlande, l'université des sciences appliquée HAMK, aussi en Finlande, l'Algebra University College en Croatie, ou encore de l’université d’Innopolis en Russie. Quelle aventure ! L'Erasmus a aussi son pendant pour les jeunes entrepreneurs, simplement intitulé &quot;Erasmus pour Jeunes Entrepreneurs&quot;. Cela leur permet d'acquérir toutes les compétences pour créer et gérer une entreprise en Europe. Les imériens jeunes entrepreneurs pourront alors acquérir, et échanger des connaissances, et des idées entrepreneuriales, avec un entrepreneur expérimenté en Europe, et auprès duquel, ils séjourneront pendant une période allant de 1 à 6 mois. Quelle formidable occasion !</source>
            <comment>Text</comment>
            <translation type="unfinished">Les imériens étudiants dans la formation &quot;Manager de systèmes informatique et robotique&quot; peuvent partir à l’étranger, dans le cadre du programme Erasmus. Plongés dans cette expérience unique et inoubliable, ils continuent d'étudier, mais dans une université ou une école d’accueil, tout en perfectionnant leur anglais, en découvrant de nouveaux pays, ainsi que de nouvelles cultures, tout en nouant de nouvelles relations. Quelle chance ! Non ? L’IMÉRIR est partenaire de plusieurs écoles et universités dans toute l’Europe, et avec lequel de riches échanges se font. Par exemple, il y a l’université des sciences appliquées de Laponie en Finlande, l'université des sciences appliquée HAMK, aussi en Finlande, l'Algebra University College en Croatie, ou encore de l’université d’Innopolis en Russie. Quelle aventure ! L'Erasmus a aussi son pendant pour les jeunes entrepreneurs, simplement intitulé &quot;Erasmus pour Jeunes Entrepreneurs&quot;. Cela leur permet d'acquérir toutes les compétences pour créer et gérer une entreprise en Europe. Les imériens jeunes entrepreneurs pourront alors acquérir, et échanger des connaissances, et des idées entrepreneuriales, avec un entrepreneur expérimenté en Europe, et auprès duquel, ils séjourneront pendant une période allant de 1 à 6 mois. Quelle formidable occasion !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Le Fablab</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>L’IMÉRIR dispose d’un fablab, un espace numérique dédié à des fins d’innovation, de prototypage, ainsi que de production à petite échelle, et qui te permet d'accéder à des imprimantes 3D, des machines-outils habituellement réservées à des professionnels, du matériel électronique, du matériel pour la réalité virtuelle, des robots humanoïdes comme moi, des cobotes, et des robots industriels. Dans cet espace, les ressources matérielles, logicielles, et humaines sont mutualisées pour prototyper, expérimenter, travailler sur les projets donnés par l'école, ainsi que t'accompagner dans ton projet de prototypage, et de création d'entreprise. Plus ton projet est ambitieux et innovant, plus il est intéressant, et plus le Fablab se donnera pour défi de t'y accompagner, dans tous ses aspects, jusqu'à sa concrétisation complète. De grands moyens pour de grandes ambitions !</source>
            <comment>Text</comment>
            <translation type="unfinished">L’IMÉRIR dispose d’un fablab, un espace numérique dédié à des fins d’innovation, de prototypage, ainsi que de production à petite échelle, et qui te permet d'accéder à des imprimantes 3D, des machines-outils habituellement réservées à des professionnels, du matériel électronique, du matériel pour la réalité virtuelle, des robots humanoïdes comme moi, des cobotes, et des robots industriels. Dans cet espace, les ressources matérielles, logicielles, et humaines sont mutualisées pour prototyper, expérimenter, travailler sur les projets donnés par l'école, ainsi que t'accompagner dans ton projet de prototypage, et de création d'entreprise. Plus ton projet est ambitieux et innovant, plus il est intéressant, et plus le Fablab se donnera pour défi de t'y accompagner, dans tous ses aspects, jusqu'à sa concrétisation complète. De grands moyens pour de grandes ambitions !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/L’admission</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Pour l’admission, c’est très simple. Il faut tout d’abord remplir le dossier d’inscription. Tu peux le trouver sur le site officiel de l'IMÉRIR ou alors en demander à mes collègues humains s’il leur en reste. Ensuite, tu dois te rendre à une des sessions d’admission organisées par l’école. Le principe est très simple: tu viens dans les locaux de l’IMÉRIR pour passer des tests mesurant ton niveau en mathématiques, en français, en anglais et en logique. Ta motivation est ensuite évaluée par un entretien individuel avec un des responsables pédagogiques de l’école. À l'issue de cette séance, l’école reviendra vers toi en cours de journée pour communiquer sa décision. Simple ! Non ? Et ce n’est pas fini. Une fois recruté, tu participes à des journées A R E, pour 'Aide à la recherche d'entreprise'. Tu seras alors accompagné par un ou plusieurs professionnels pour faire un CV et une lettre de motivation en béton. Tu apprendras également comment te comporter et réagir face à un recruteur pour mettre toutes les chances de ton côté. Voilà ! Tu sais tout.</source>
            <comment>Text</comment>
            <translation type="unfinished">Pour l’admission, c’est très simple. Il faut tout d’abord remplir le dossier d’inscription. Tu peux le trouver sur le site officiel de l'IMÉRIR ou alors en demander à mes collègues humains s’il leur en reste. Ensuite, tu dois te rendre à une des sessions d’admission organisées par l’école. Le principe est très simple: tu viens dans les locaux de l’IMÉRIR pour passer des tests mesurant ton niveau en mathématiques, en français, en anglais et en logique. Ta motivation est ensuite évaluée par un entretien individuel avec un des responsables pédagogiques de l’école. À l'issue de cette séance, l’école reviendra vers toi en cours de journée pour communiquer sa décision. Simple ! Non ? Et ce n’est pas fini. Une fois recruté, tu participes à des journées A R E, pour 'Aide à la recherche d'entreprise'. Tu seras alors accompagné par un ou plusieurs professionnels pour faire un CV et une lettre de motivation en béton. Tu apprendras également comment te comporter et réagir face à un recruteur pour mettre toutes les chances de ton côté. Voilà ! Tu sais tout.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/L’alternance</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Outre les domaines qui y sont enseignés, l’IMÉRIR a pour objectif la professionnalisation de ses étudiants, vers des postes d'ingénieurs, de chefs de projet, et de managers. C'est pour cette raison, que toutes les formations dispensées par l'IMÉRIR, se font en alternance. L’alternance est un dispositif de formation, combinant l’acquisition de nouveaux savoirs, et de nouvelles compétences au sein de l’école, à une mise en pratique directe dans l’entreprise en qualité de salarié. L'alternance, ce n'est que des avantages ! Pour l'étudiant, les frais de scolarité sont gratuits, et tu es salarié de l'entreprise, ce qui fait que tu touches ton salaire, et bénéficies des avantages accordés par l'entreprise. Pour l'entreprise, cette dernière transmet son savoir-faire à un collaborateur intégré progressivement dans sa charge et avec des coûts de recrutement maitrisés. Du gagnant-gagnant, en somme ! Il existe 2 types de contrat de travail en alternance: le contrat d'apprentissage, et le contrat de professionnalisation. Les différences entre les deux sont purement administratives. Donc vas-y, go !</source>
            <comment>Text</comment>
            <translation type="unfinished">Outre les domaines qui y sont enseignés, l’IMÉRIR a pour objectif la professionnalisation de ses étudiants, vers des postes d'ingénieurs, de chefs de projet, et de managers. C'est pour cette raison, que toutes les formations dispensées par l'IMÉRIR, se font en alternance. L’alternance est un dispositif de formation, combinant l’acquisition de nouveaux savoirs, et de nouvelles compétences au sein de l’école, à une mise en pratique directe dans l’entreprise en qualité de salarié. L'alternance, ce n'est que des avantages ! Pour l'étudiant, les frais de scolarité sont gratuits, et tu es salarié de l'entreprise, ce qui fait que tu touches ton salaire, et bénéficies des avantages accordés par l'entreprise. Pour l'entreprise, cette dernière transmet son savoir-faire à un collaborateur intégré progressivement dans sa charge et avec des coûts de recrutement maitrisés. Du gagnant-gagnant, en somme ! Il existe 2 types de contrat de travail en alternance: le contrat d'apprentissage, et le contrat de professionnalisation. Les différences entre les deux sont purement administratives. Donc vas-y, go !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Message de bienvenue au prospect</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</source>
            <comment>Text</comment>
            <translation type="unfinished">Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Nos formations</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Aujourd’hui, L’IMÉRIR dispense 3 formations dans les domaines de l’informatique et de la robotique. Sa principale est &quot;Manager de systèmes informatique et robotique&quot; (en abrégé MSIR). C'est une formation Bac +5 qui se déroule en 3 ans après un BTS, un DUT ou une prépa scientifique et technique, qui est polyvalente car conjuguant l'acquisition des compétences en informatique, en robotique et en management pour permettre aux étudiants de diriger n’importe quel projet informatique et robotique dès l’obtention de leur diplôme. Pour tous ceux qui ne disposent pas du bagage requis: pas de panique ! L'IMÉRIR dispose d'une formation Bac +2 intitulée &quot;Analyste développeur d'applications informatiques&quot; qui se déroule en 2 ans après un baccalauréat général, technologique ou professionnel et qui permet aux étudiants l'acquisition des bases en informatique, en conception assistée par ordinateur (CAO), en mécanique et en électronique, tout en se professionnalisant. Ces 2 formations sont certifiantes par un diplôme inscrit au Répertoire National de la Certification Professionnelle (RNCP), et sont donc reconnues par l’Etat. L'IMÉRIR dispose également d'une troisième formation, la &quot;Licence informatique spécialité robotique de prototypage&quot;, formation Bac +3 qui se déroule après l'obtention d'un diplôme ou d'un titre professionnel de niveau Bac +2. Cette formation couvre les principaux domaines de l'informatique (comme le développement, les réseaux ou encore l'architecture des machines) mais avec une spécialisation dans les domaines de la robotique. Point intéressant ! Il vous est possible de valider les formations &quot;Manager de systèmes informatique et robotique&quot; et &quot;Licence informatique spécialité robotique de prototypage&quot; en validation des acquis de l'experience (en abrégé VAE). Et ça, c'est cool comme Ra's al Ghul !</source>
            <comment>Text</comment>
            <translation type="unfinished">Aujourd’hui, L’IMÉRIR dispense 3 formations dans les domaines de l’informatique et de la robotique. Sa principale est &quot;Manager de systèmes informatique et robotique&quot; (en abrégé MSIR). C'est une formation Bac +5 qui se déroule en 3 ans après un BTS, un DUT ou une prépa scientifique et technique, qui est polyvalente car conjuguant l'acquisition des compétences en informatique, en robotique et en management pour permettre aux étudiants de diriger n’importe quel projet informatique et robotique dès l’obtention de leur diplôme. Pour tous ceux qui ne disposent pas du bagage requis: pas de panique ! L'IMÉRIR dispose d'une formation Bac +2 intitulée &quot;Analyste développeur d'applications informatiques&quot; qui se déroule en 2 ans après un baccalauréat général, technologique ou professionnel et qui permet aux étudiants l'acquisition des bases en informatique, en conception assistée par ordinateur (CAO), en mécanique et en électronique, tout en se professionnalisant. Ces 2 formations sont certifiantes par un diplôme inscrit au Répertoire National de la Certification Professionnelle (RNCP), et sont donc reconnues par l’Etat. L'IMÉRIR dispose également d'une troisième formation, la &quot;Licence informatique spécialité robotique de prototypage&quot;, formation Bac +3 qui se déroule après l'obtention d'un diplôme ou d'un titre professionnel de niveau Bac +2. Cette formation couvre les principaux domaines de l'informatique (comme le développement, les réseaux ou encore l'architecture des machines) mais avec une spécialisation dans les domaines de la robotique. Point intéressant ! Il vous est possible de valider les formations &quot;Manager de systèmes informatique et robotique&quot; et &quot;Licence informatique spécialité robotique de prototypage&quot; en validation des acquis de l'experience (en abrégé VAE). Et ça, c'est cool comme Ra's al Ghul !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Nous contacter</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Pour nous contacter, rien de plus simple. Tu peux nous téléphoner au 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux également nous envoyer un message depuis le site officiel de l'école dans le menu &quot;Contact&quot;, et nous n'hésiterons pas à te lire et à te répondre. Si tu es par contre très curieux, tu peux aussi venir nous voir directement dans nos locaux. Ils sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. Et voilà ! Maintenant, tu peux nous contacter quand tu veux.</source>
            <comment>Text</comment>
            <translation type="unfinished">Pour nous contacter, rien de plus simple. Tu peux nous téléphoner au 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux également nous envoyer un message depuis le site officiel de l'école dans le menu &quot;Contact&quot;, et nous n'hésiterons pas à te lire et à te répondre. Si tu es par contre très curieux, tu peux aussi venir nous voir directement dans nos locaux. Ils sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. Et voilà ! Maintenant, tu peux nous contacter quand tu veux.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Qui sommes nous ?</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>L’IMÉRIR est une école supérieure de la C C I, pour 'Chambre de commerce et d'industrie', des Pyrénées Orientales, fondée en 1981, et basée à Perpignan, plus exactement sur 'Purple campus'. L’IMÉRIR prépare aux métiers de la robotique, de l’informatique, des objets connectés, et de l'intelligence artificielle. Le management et la gestion de projets y sont également abordés. Notre école dispose aussi d'un fablab, un lieu où sont disponibles des imprimantes 3D, une découpeuse laser, des robots industriels, comme mes amis robots de chez Kouka, Fanuc, et Staubli, des fers à souder, du matériel électronique et tous ce qui est nécessaire, pour le développement de projets maikeur, et qui sont utiles pour réaliser des projets d'école, des projets personnels, voire des projets d'ordre professionnel. L’IMÉRIR cultive aussi des partenariats, comme avec le groupe école Pratique à Marseille, le centre de formation de la C C I Marseille-Provence.</source>
            <comment>Text</comment>
            <translation type="unfinished">L’IMÉRIR est une école supérieure de la C C I, pour 'Chambre de commerce et d'industrie', des Pyrénées Orientales, fondée en 1981, et basée à Perpignan, plus exactement sur 'Purple campus'. L’IMÉRIR prépare aux métiers de la robotique, de l’informatique, des objets connectés, et de l'intelligence artificielle. Le management et la gestion de projets y sont également abordés. Notre école dispose aussi d'un fablab, un lieu où sont disponibles des imprimantes 3D, une découpeuse laser, des robots industriels, comme mes amis robots de chez Kouka, Fanuc, et Staubli, des fers à souder, du matériel électronique et tous ce qui est nécessaire, pour le développement de projets maikeur, et qui sont utiles pour réaliser des projets d'école, des projets personnels, voire des projets d'ordre professionnel. L’IMÉRIR cultive aussi des partenariats, comme avec le groupe école Pratique à Marseille, le centre de formation de la C C I Marseille-Provence.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Remise des diplômes</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Chaque année, l'IMÉRIR organise, une cérémonie de remise des diplômes, pour la promotion sortante. Elle a lieu, tous les ans, au palais des rois de Mayorque, à Perpignan. Lors de cette cérémonie, la promotion sortante, est diplômée, et la promotion entrante, est adoubée. Ainsi, après un discours très inspiré de l'équipe dirigeante de l'IMÉRIR, et du parrain de la promotion, chacun des diplômés, reçoit son diplôme, de la main de l'équipe pédagogique, sur les estrades. Une fois cela fait, la nouvelle promotion, celle qui entre à l'IMÉRIR, se présente en masse sur les estrades, prend la pose, puis se fait photographier, pour la postérité. Un discours de clôture accompagne, bien sûr, la fin de cette cérémonie. Une fois cette dernière terminée, les promotions sortante et entrante, partagent un verre ensemble, en compagnie de l'équipe pédagogique de l'école, de son équipe dirigeante, des parrains des promotions sortante et entrante, et de l'association &quot;Alumni IMÉRIR&quot;. Cool ! Quel moment festif, et convivial !</source>
            <comment>Text</comment>
            <translation type="unfinished">Chaque année, l'IMÉRIR organise, une cérémonie de remise des diplômes, pour la promotion sortante. Elle a lieu, tous les ans, au palais des rois de Mayorque, à Perpignan. Lors de cette cérémonie, la promotion sortante, est diplômée, et la promotion entrante, est adoubée. Ainsi, après un discours très inspiré de l'équipe dirigeante de l'IMÉRIR, et du parrain de la promotion, chacun des diplômés, reçoit son diplôme, de la main de l'équipe pédagogique, sur les estrades. Une fois cela fait, la nouvelle promotion, celle qui entre à l'IMÉRIR, se présente en masse sur les estrades, prend la pose, puis se fait photographier, pour la postérité. Un discours de clôture accompagne, bien sûr, la fin de cette cérémonie. Une fois cette dernière terminée, les promotions sortante et entrante, partagent un verre ensemble, en compagnie de l'équipe pédagogique de l'école, de son équipe dirigeante, des parrains des promotions sortante et entrante, et de l'association &quot;Alumni IMÉRIR&quot;. Cool ! Quel moment festif, et convivial !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/S'inscrire</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Pour t'inscrire, c'est très facile. Il te suffit de remplir un dossier d'inscription, depuis le site officiel de l'IMÉRIR, dans le menu &quot;Admissions&quot;, puis le sous-menu &quot;Demander mon dossier&quot;. Tu renseignes alors, la formation que tu demandes, ton nom de famille, ton prénom, et ton adresse email. Ton dossier d'inscription, te sera alors envoyé par email, et tu dois alors l'imprimer. Tu peux aussi demander, à mes collègues humains, s'ils n'en ont pas à disposition. Il te suffit alors de le remplir, puis de nous le retourner, avec tous les documents demandés, par la Poste, à l'adresse suivante: IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Je répète, IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Une fois le dossier d'inscription reçu, l'école traite ta demande. Il faut que tu aies fait, des études scientifiques, et que tu aies bien réussi ta scolarité, pour que ton dossier soit accepté. S'il est accepté, l'IMÉRIR t'invite, pour passer une session d'admission, dans ses locaux. Ton esprit logique, ta maitrise de l'anglais, ta maitrise du français, et ta capacité de raisonnement, sont alors mis à rude épreuve. Finalement, ta motivation est évaluée, au cours d'un entretien individuel avec l'équipe pédagogique de l'école. Dans la journée, tu es ensuite, informé de la décision de l'IMÉRIR, de te laisser intégrer l'école comme étudiant, ou non. C'est donc tout simple !</source>
            <comment>Text</comment>
            <translation type="unfinished">Pour t'inscrire, c'est très facile. Il te suffit de remplir un dossier d'inscription, depuis le site officiel de l'IMÉRIR, dans le menu &quot;Admissions&quot;, puis le sous-menu &quot;Demander mon dossier&quot;. Tu renseignes alors, la formation que tu demandes, ton nom de famille, ton prénom, et ton adresse email. Ton dossier d'inscription, te sera alors envoyé par email, et tu dois alors l'imprimer. Tu peux aussi demander, à mes collègues humains, s'ils n'en ont pas à disposition. Il te suffit alors de le remplir, puis de nous le retourner, avec tous les documents demandés, par la Poste, à l'adresse suivante: IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Je répète, IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Une fois le dossier d'inscription reçu, l'école traite ta demande. Il faut que tu aies fait, des études scientifiques, et que tu aies bien réussi ta scolarité, pour que ton dossier soit accepté. S'il est accepté, l'IMÉRIR t'invite, pour passer une session d'admission, dans ses locaux. Ton esprit logique, ta maitrise de l'anglais, ta maitrise du français, et ta capacité de raisonnement, sont alors mis à rude épreuve. Finalement, ta motivation est évaluée, au cours d'un entretien individuel avec l'équipe pédagogique de l'école. Dans la journée, tu es ensuite, informé de la décision de l'IMÉRIR, de te laisser intégrer l'école comme étudiant, ou non. C'est donc tout simple !</translation>
        </message>
    </context>
</TS>
