<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR">
    <context>
        <name>behavior_1/behavior.xar:/Adresse postale</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Donc, les locaux de l'IMÉRIR, sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. L'école est ouverte, de 8 heures 15 à 17 heures 15, du lundi au vendredi. Donc, si tu es curieux, tu peux venir nous voir directement.</source>
            <comment>Text</comment>
            <translation type="unfinished">Donc, les locaux de l'IMÉRIR, sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. L'école est ouverte, de 8 heures 15 à 17 heures 15, du lundi au vendredi. Donc, si tu es curieux, tu peux venir nous voir directement.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Animated Say</name>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="vanished">Bonjour</translation>
        </message>
        <message>
            <source>Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</source>
            <comment>Text</comment>
            <translation type="obsolete">Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</translation>
        </message>
        <message>
            <source>Moi aussi</source>
            <comment>Text</comment>
            <translation type="obsolete">Moi aussi</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Animated Say (1)</name>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="vanished">Bonjour</translation>
        </message>
        <message>
            <source>Oh !!!!</source>
            <comment>Text</comment>
            <translation type="obsolete">Oh !!!!</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Animated Say (2)</name>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="vanished">Bonjour</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Association des anciens</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Les étudiants diplômés de l'IMÉRIR, constituent un grand réseau professionel, concrétisé sous la forme d'une association loi de 1901, nommé &quot;Alumni IMÉRIR&quot;. &quot;Alumni&quot;, signifie &quot;anciens élèves&quot;, en anglais. Créée en 1994, cette association, a pour tâche de maintenir le liens, entre tous les diplômés. Elle mène des actions, vers les diplômés de l'école, vers les imériens, vers les entreprises partenaires, et vers les cabinets de recrutement. &quot;Alumni IMÉRIR&quot; dispose, également, d'une adresse email, d'un numéro de téléphone, d'une page Facebook, d'une page Line keuh dine, et d'une boutique en ligne. Wahou ! Aujourd'hui, le réseau des anciens étudiants de l'IMÉRIR, comporte 1300 membres, répartis, dans tous les secteurs économiques (banques, assurances, santé, recherche, enseignement, sociétés de service informatique...). Vraiment ! Comme c'est top !</source>
            <comment>Text</comment>
            <translation type="unfinished">Les étudiants diplômés de l'IMÉRIR, constituent un grand réseau professionel, concrétisé sous la forme d'une association loi de 1901, nommé &quot;Alumni IMÉRIR&quot;. &quot;Alumni&quot;, signifie &quot;anciens élèves&quot;, en anglais. Créée en 1994, cette association, a pour tâche de maintenir le liens, entre tous les diplômés. Elle mène des actions, vers les diplômés de l'école, vers les imériens, vers les entreprises partenaires, et vers les cabinets de recrutement. &quot;Alumni IMÉRIR&quot; dispose, également, d'une adresse email, d'un numéro de téléphone, d'une page Facebook, d'une page Line keuh dine, et d'une boutique en ligne. Wahou ! Aujourd'hui, le réseau des anciens étudiants de l'IMÉRIR, comporte 1300 membres, répartis, dans tous les secteurs économiques (banques, assurances, santé, recherche, enseignement, sociétés de service informatique...). Vraiment ! Comme c'est top !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Cybersécurité</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;cybersécurité&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Cybersécurité&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans les réseaux informatiques, de protéger les infrastructures réseaux, ainsi que les objets connectés, et à contrer des attaques de hackeurs. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici la &quot;Cybersécurité&quot;. C'est simple comme bonjour !</source>
            <comment>Text</comment>
            <translation type="unfinished">Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;cybersécurité&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Cybersécurité&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans les réseaux informatiques, de protéger les infrastructures réseaux, ainsi que les objets connectés, et à contrer des attaques de hackeurs. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici la &quot;Cybersécurité&quot;. C'est simple comme bonjour !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Erasmus</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Les imériens étudiants dans la formation &quot;Manager de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;) peuvent partir à l’étranger, dans le cadre du programme Erasmus. Plongés dans cette expérience unique et inoubliable, ils continuent d'étudier, mais dans une université ou une école d’accueil, tout en perfectionnant leur anglais, en découvrant de nouveaux pays, ainsi que de nouvelles cultures, tout en nouant de nouvelles relations. Quelle chance ! Non ? L’IMÉRIR est partenaire de plusieurs écoles et universités dans toute l’Europe, et avec lequel de riches échanges se font. Par exemple, il y a l’université des sciences appliquées de Laponie en Finlande, l'université des sciences appliquée HAMK, aussi en Finlande, l'Algebra University College en Croatie, ou encore de l’université d’Innopolis en Russie. Quelle aventure ! L'Erasmus a aussi son pendant pour les jeunes entrepreneurs, simplement intitulé &quot;Erasmus pour Jeunes Entrepreneurs&quot;. Cela leur permet d'acquérir toutes les compétences pour créer et gérer une entreprise en Europe. Les imériens jeunes entrepreneurs pourront alors acquérir, et échanger des connaissances, et des idées entrepreneuriales, avec un entrepreneur expérimenté en Europe, et auprès duquel, ils séjourneront pendant une période allant de 1 à 6 mois. Quelle formidable occasion !</source>
            <comment>Text</comment>
            <translation type="unfinished">Les imériens étudiants dans la formation &quot;Manager de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;) peuvent partir à l’étranger, dans le cadre du programme Erasmus. Plongés dans cette expérience unique et inoubliable, ils continuent d'étudier, mais dans une université ou une école d’accueil, tout en perfectionnant leur anglais, en découvrant de nouveaux pays, ainsi que de nouvelles cultures, tout en nouant de nouvelles relations. Quelle chance ! Non ? L’IMÉRIR est partenaire de plusieurs écoles et universités dans toute l’Europe, et avec lequel de riches échanges se font. Par exemple, il y a l’université des sciences appliquées de Laponie en Finlande, l'université des sciences appliquée HAMK, aussi en Finlande, l'Algebra University College en Croatie, ou encore de l’université d’Innopolis en Russie. Quelle aventure ! L'Erasmus a aussi son pendant pour les jeunes entrepreneurs, simplement intitulé &quot;Erasmus pour Jeunes Entrepreneurs&quot;. Cela leur permet d'acquérir toutes les compétences pour créer et gérer une entreprise en Europe. Les imériens jeunes entrepreneurs pourront alors acquérir, et échanger des connaissances, et des idées entrepreneuriales, avec un entrepreneur expérimenté en Europe, et auprès duquel, ils séjourneront pendant une période allant de 1 à 6 mois. Quelle formidable occasion !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Formulaire</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Ainsi, tu peux aussi nous envoyer un message, en remplissant le formulaire disponible, sur le site officiel de l'IMÉRIR. Il se trouve dans le menu &quot;Nous contacter&quot;. Tu peux nous poser, toutes les questions, que tu as en tête, et nous te répondrons, dans les plus brefs délais.</source>
            <comment>Text</comment>
            <translation type="unfinished">Ainsi, tu peux aussi nous envoyer un message, en remplissant le formulaire disponible, sur le site officiel de l'IMÉRIR. Il se trouve dans le menu &quot;Nous contacter&quot;. Tu peux nous poser, toutes les questions, que tu as en tête, et nous te répondrons, dans les plus brefs délais.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Informations supplémentaires sur le fablab</name>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="obsolete">Bonjour</translation>
        </message>
        <message>
            <source>Le fablab de l’IMÉRIR, est situé juste en face, du Purple campus de Perpignan, où se trouve l’IMÉRIR. Il dispose actuellement de robots industriels, d'imprimantes 3D, d'une découpeuse laser, d'une fraiseuse numérique, de matériel électronique, et de plein d'autres choses encore. Impressionnant ! Animé par les apprentis embauchés à l'IMÉRIR, le responsable des études de l'école (qui est aussi, le responsable informatique de l'école), Monsieur Gilles Mateu, et un professeur permanant de l'IMÉRIR, Monsieur Adrien Datas. Ils sont tous là, pour  t'aider dans la réalisation de tes projets écoles ou personels, pour te faire monter en compétence, et pour te faire apprendre, des choses passionnantes. Tu l'as compris ! On trouve tout dans ce tiers-lieu, pour bricoler, prototyper, et réaliser des projets maikeur. Alors toi aussi, jettes toi dans l'aventure fablab !</source>
            <comment>Text</comment>
            <translation type="obsolete">Le fablab de l’IMÉRIR, est situé juste en face, du Purple campus de Perpignan, où se trouve l’IMÉRIR. Il dispose actuellement de robots industriels, d'imprimantes 3D, d'une découpeuse laser, d'une fraiseuse numérique, de matériel électronique, et de plein d'autres choses encore. Impressionnant ! Animé par les apprentis embauchés à l'IMÉRIR, le responsable des études de l'école (qui est aussi, le responsable informatique de l'école), Monsieur Gilles Mateu, et un professeur permanant de l'IMÉRIR, Monsieur Adrien Datas. Ils sont tous là, pour  t'aider dans la réalisation de tes projets écoles ou personels, pour te faire monter en compétence, et pour te faire apprendre, des choses passionnantes. Tu l'as compris ! On trouve tout dans ce tiers-lieu, pour bricoler, prototyper, et réaliser des projets maikeur. Alors toi aussi, jettes toi dans l'aventure fablab !</translation>
        </message>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Le fablab de l’IMÉRIR, est situé juste en face, du Purple campus de Perpignan, où se trouve l’IMÉRIR. Il dispose actuellement de robots industriels, d'imprimantes 3D, d'une découpeuse laser, d'une fraiseuse numérique, de matériel électronique, et de plein d'autres choses encore. Impressionnant ! Animé par les apprentis embauchés à l'IMÉRIR, le responsable des études de l'école (qui est aussi, le responsable informatique de l'école), Monsieur Gilles Mateu, et un professeur permanant de l'IMÉRIR, Monsieur Adrien Datasse. Ils sont tous là, pour  t'aider dans la réalisation de tes projets écoles ou personels, pour te faire monter en compétence, et pour te faire apprendre, des choses passionnantes. Tu l'as compris ! On trouve tout dans ce tiers-lieu, pour bricoler, prototyper, et réaliser des projets maikeur. Alors toi aussi, jettes toi dans l'aventure fablab !</source>
            <comment>Text</comment>
            <translation type="unfinished">Le fablab de l’IMÉRIR, est situé juste en face, du Purple campus de Perpignan, où se trouve l’IMÉRIR. Il dispose actuellement de robots industriels, d'imprimantes 3D, d'une découpeuse laser, d'une fraiseuse numérique, de matériel électronique, et de plein d'autres choses encore. Impressionnant ! Animé par les apprentis embauchés à l'IMÉRIR, le responsable des études de l'école (qui est aussi, le responsable informatique de l'école), Monsieur Gilles Mateu, et un professeur permanant de l'IMÉRIR, Monsieur Adrien Datasse. Ils sont tous là, pour  t'aider dans la réalisation de tes projets écoles ou personels, pour te faire monter en compétence, et pour te faire apprendre, des choses passionnantes. Tu l'as compris ! On trouve tout dans ce tiers-lieu, pour bricoler, prototyper, et réaliser des projets maikeur. Alors toi aussi, jettes toi dans l'aventure fablab !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Intelligence artificielle</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;Intelligence artificielle&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Intelligence artificielle&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans le machine learning, la complexité algorithmique, l'optimisation algorithmique, les systèmes experts, et le deep learning. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici l'&quot;Intelligence artificielle&quot;. C'est simple comme bonjour !</source>
            <comment>Text</comment>
            <translation type="unfinished">Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;Intelligence artificielle&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Intelligence artificielle&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans le machine learning, la complexité algorithmique, l'optimisation algorithmique, les systèmes experts, et le deep learning. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici l'&quot;Intelligence artificielle&quot;. C'est simple comme bonjour !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Internet des objets</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;Internet des objets&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Internet des objets&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans la conception d'objets connectés, le claoude, l'éléctronique, les infrastructures distribuées, le blockchain, ainsi que le développement mobile, et le droit des objets connectés et des logiciels. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici l'&quot;Internet des objets&quot;. C'est simple comme bonjour !</source>
            <comment>Text</comment>
            <translation type="unfinished">Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;Internet des objets&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Internet des objets&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans la conception d'objets connectés, le claoude, l'éléctronique, les infrastructures distribuées, le blockchain, ainsi que le développement mobile, et le droit des objets connectés et des logiciels. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici l'&quot;Internet des objets&quot;. C'est simple comme bonjour !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Le Fablab</name>
        <message>
            <source>L’IMÉRIR dispose d’un fablab, un espace numérique dédié à des fins d’innovation, de prototypage, ainsi que de production à petite échelle, et qui te permet d'accéder à des imprimantes 3D, des machines-outils habituellement réservées à des professionnels, du matériel électronique, du matériel pour la réalité virtuelle, des robots humanoïdes comme moi, des cobotes, et des robots industriels. Dans cet espace, les ressources matérielles, logicielles, et humaines sont mutualisées pour prototyper, expérimenter, travailler sur les projets donnés par l'école, ainsi que t'accompagner dans ton projet de prototypage, et de création d'entreprise. Plus ton projet est ambitieux et innovant, plus il est intéressant, et plus le Fablab se donnera pour défi de t'y accompagner, dans tous ses aspects, jusqu'à sa concrétisation complète. De grands moyens pour de grandes ambitions !</source>
            <comment>Text</comment>
            <translation type="obsolete">L’IMÉRIR dispose d’un fablab, un espace numérique dédié à des fins d’innovation, de prototypage, ainsi que de production à petite échelle, et qui te permet d'accéder à des imprimantes 3D, des machines-outils habituellement réservées à des professionnels, du matériel électronique, du matériel pour la réalité virtuelle, des robots humanoïdes comme moi, des cobotes, et des robots industriels. Dans cet espace, les ressources matérielles, logicielles, et humaines sont mutualisées pour prototyper, expérimenter, travailler sur les projets donnés par l'école, ainsi que t'accompagner dans ton projet de prototypage, et de création d'entreprise. Plus ton projet est ambitieux et innovant, plus il est intéressant, et plus le Fablab se donnera pour défi de t'y accompagner, dans tous ses aspects, jusqu'à sa concrétisation complète. De grands moyens pour de grandes ambitions !</translation>
        </message>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>L’IMÉRIR dispose d’un fablab, un espace numérique dédié à des fins d’innovation, de prototypage, ainsi que de production à petite échelle, et qui te permet d'accéder à des imprimantes 3D, des machines-outils habituellement réservées à des professionnels, du matériel électronique, du matériel pour la réalité virtuelle, des robots humanoïdes comme moi, des cobotes, et des robots industriels. Dans cet espace, les ressources matérielles, logicielles, et humaines sont mutualisées pour prototyper, expérimenter, travailler sur les projets donnés par l'école, ainsi que t'accompagner dans ton projet de prototypage, et de création d'entreprise. Plus ton projet est ambitieux et innovant, plusse il est intéressant, et plus le Fablab se donnera pour défi de t'y accompagner, dans tous ses aspects, jusqu'à sa concrétisation complète. De grands moyens pour de grandes ambitions !</source>
            <comment>Text</comment>
            <translation type="unfinished">L’IMÉRIR dispose d’un fablab, un espace numérique dédié à des fins d’innovation, de prototypage, ainsi que de production à petite échelle, et qui te permet d'accéder à des imprimantes 3D, des machines-outils habituellement réservées à des professionnels, du matériel électronique, du matériel pour la réalité virtuelle, des robots humanoïdes comme moi, des cobotes, et des robots industriels. Dans cet espace, les ressources matérielles, logicielles, et humaines sont mutualisées pour prototyper, expérimenter, travailler sur les projets donnés par l'école, ainsi que t'accompagner dans ton projet de prototypage, et de création d'entreprise. Plus ton projet est ambitieux et innovant, plusse il est intéressant, et plus le Fablab se donnera pour défi de t'y accompagner, dans tous ses aspects, jusqu'à sa concrétisation complète. De grands moyens pour de grandes ambitions !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/License informatique option robotique de prototypage</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="unfinished">Bonjour</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/L’alternance</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Outre les domaines qui y sont enseignés, l’IMÉRIR a pour objectif la professionnalisation de ses étudiants, vers des postes d'ingénieurs, de chefs de projet, et de managers. C'est pour cette raison, que toutes les formations dispensées par l'IMÉRIR, se font en alternance. L’alternance est un dispositif de formation, combinant l’acquisition de nouveaux savoirs, et de nouvelles compétences au sein de l’école, à une mise en pratique directe dans l’entreprise en qualité de salarié. L'alternance, ce n'est que des avantages ! Pour l'étudiant, les frais de scolarité sont gratuits, et tu es salarié de l'entreprise, ce qui fait que tu touches ton salaire, et bénéficies des avantages accordés par l'entreprise. Pour l'entreprise, cette dernière transmet son savoir-faire à un collaborateur intégré progressivement dans sa charge et avec des coûts de recrutement maitrisés. Du gagnant-gagnant, en somme ! Il existe 2 types de contrat de travail en alternance: le contrat d'apprentissage, et le contrat de professionnalisation. Les différences entre les deux sont purement administratives. Donc vas-y, go !</source>
            <comment>Text</comment>
            <translation type="unfinished">Outre les domaines qui y sont enseignés, l’IMÉRIR a pour objectif la professionnalisation de ses étudiants, vers des postes d'ingénieurs, de chefs de projet, et de managers. C'est pour cette raison, que toutes les formations dispensées par l'IMÉRIR, se font en alternance. L’alternance est un dispositif de formation, combinant l’acquisition de nouveaux savoirs, et de nouvelles compétences au sein de l’école, à une mise en pratique directe dans l’entreprise en qualité de salarié. L'alternance, ce n'est que des avantages ! Pour l'étudiant, les frais de scolarité sont gratuits, et tu es salarié de l'entreprise, ce qui fait que tu touches ton salaire, et bénéficies des avantages accordés par l'entreprise. Pour l'entreprise, cette dernière transmet son savoir-faire à un collaborateur intégré progressivement dans sa charge et avec des coûts de recrutement maitrisés. Du gagnant-gagnant, en somme ! Il existe 2 types de contrat de travail en alternance: le contrat d'apprentissage, et le contrat de professionnalisation. Les différences entre les deux sont purement administratives. Donc vas-y, go !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Message de bienvenue au prospect</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</source>
            <comment>Text</comment>
            <translation type="unfinished">Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</translation>
        </message>
        <message>
            <source>DDFF</source>
            <comment>Text</comment>
            <translation type="obsolete">DDFF</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Message de bienvenue au prospect
</name>
        <message>
            <source>Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</source>
            <comment>Text</comment>
            <translation type="obsolete">Bonjour à toi, humain ! Je m'appelle Pepper. Je suis un robot humanoïde, un système complexe associant la mécanique, l'électronique, et l'informatique. L'informatique ? Parlons-en ! Ma grande force, c'est l'intelligence qu'on m'a développée, et qui me permet de te parler et de t'exposer des choses. Mais qui me permet également de recueillir ton avis, de te répondre à une question, et de réagir selon les différentes émotions que tu peux éprouver. Mon intelligence, tu l'as compris, a été programmé, par des programmeurs. Et toi aussi, tu peux apprendre le développement informatique, pour que développer un robot comme moi, n'ait plus de secrets pour toi. Tu l'as compris, je suis ici en tant qu'ambassadeur de l'IMÉRIR. Acronyme d'institut méditerranéen d'étude et de recherche en informatique et robotique, cette école te permet, justement, de te former aux métiers du développement informatique, de la robotique, des objets connectés et de l'intelligence artificielle, pour que toi aussi, tu sois capable de me programmer, voire, de développer des choses plus balèzes encore. Quelles choses passionnantes !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Message de remerciements, d'information et d'au revoir</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Merci de m'avoir laissé te présenter l'IMÉRIR. J'espère que ça a attisé ta curiosité dans les domaines de l'informatique, de la robotique, des objets connectés et de l'intelligence artificielle. Si tu es intéressé, tu peux demander à mes collègues humains des précisions supplémentaires, les plaquettes de présentation détaillée de chacune des formations dispensées par l'école, voire aussi un dossier d'inscription pour devenir étudiant de notre école et toutes informations supplémentaires. Tu peux aussi à tout moment demander les renseignements et les informations que tu veux, soit en te rendant sur le site officiel de l'IMÉRIR, soit en téléphonant au 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux aussi venir nous voir directement dans nos locaux. Ils sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. Au revoir, j'espère te revoir très vite.</source>
            <comment>Text</comment>
            <translation type="unfinished">Merci de m'avoir laissé te présenter l'IMÉRIR. J'espère que ça a attisé ta curiosité dans les domaines de l'informatique, de la robotique, des objets connectés et de l'intelligence artificielle. Si tu es intéressé, tu peux demander à mes collègues humains des précisions supplémentaires, les plaquettes de présentation détaillée de chacune des formations dispensées par l'école, voire aussi un dossier d'inscription pour devenir étudiant de notre école et toutes informations supplémentaires. Tu peux aussi à tout moment demander les renseignements et les informations que tu veux, soit en te rendant sur le site officiel de l'IMÉRIR, soit en téléphonant au 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux aussi venir nous voir directement dans nos locaux. Ils sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. Au revoir, j'espère te revoir très vite.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Nos formations</name>
        <message>
            <source>Aujourd’hui, L’IMÉRIR dispense 3 formations dans les domaines de l’informatique et de la robotique. Sa principale est &quot;Manager de systèmes informatique et robotique&quot; (en abrégé MSIR). C'est une formation Bac +5 qui se déroule en 3 ans après un brevet de technicien supérieur (ou &quot;BTS&quot;), un bachelor universitaire de technologie (ou &quot;B U T&quot;) ou une prépa scientifique et technique, qui est polyvalente car conjuguant l'acquisition des compétences en informatique, en robotique et en management pour permettre aux étudiants de diriger n’importe quel projet informatique et robotique dès l’obtention de leur diplôme. Pour tous ceux qui ne disposent pas du bagage requis: pas de panique ! L'IMÉRIR dispose d'une formation Bac +2 intitulée &quot;Analyste développeur d'applications informatiques&quot; qui se déroule en 2 ans après un baccalauréat général, technologique ou professionnel et qui permet aux étudiants l'acquisition des bases en informatique, en conception assistée par ordinateur (ou &quot;C A O&quot;), en mécanique et en électronique, tout en se professionnalisant. Ces 2 formations sont certifiantes par un diplôme inscrit au Répertoire National de la Certification Professionnelle (ou &quot;RNCP&quot;), et sont donc reconnues par l’Etat. L'IMÉRIR dispose également d'une troisième formation, la &quot;Licence informatique spécialité robotique de prototypage&quot;, formation Bac +3 qui se déroule après l'obtention d'un diplôme ou d'un titre professionnel de niveau Bac +2. Cette formation couvre les principaux domaines de l'informatique (comme le développement, les réseaux ou encore l'architecture des machines) mais avec une spécialisation dans les domaines de la robotique. Point intéressant ! Il vous est possible de valider les formations &quot;Manager de systèmes informatique et robotique&quot; et &quot;Licence informatique spécialité robotique de prototypage&quot; en validation des acquis de l'experience (en abrégé &quot;V A E&quot;). Et ça, c'est cool comme Ra's al Ghul !</source>
            <comment>Text</comment>
            <translation type="obsolete">Aujourd’hui, L’IMÉRIR dispense 3 formations dans les domaines de l’informatique et de la robotique. Sa principale est &quot;Manager de systèmes informatique et robotique&quot; (en abrégé MSIR). C'est une formation Bac +5 qui se déroule en 3 ans après un brevet de technicien supérieur (ou &quot;BTS&quot;), un bachelor universitaire de technologie (ou &quot;B U T&quot;) ou une prépa scientifique et technique, qui est polyvalente car conjuguant l'acquisition des compétences en informatique, en robotique et en management pour permettre aux étudiants de diriger n’importe quel projet informatique et robotique dès l’obtention de leur diplôme. Pour tous ceux qui ne disposent pas du bagage requis: pas de panique ! L'IMÉRIR dispose d'une formation Bac +2 intitulée &quot;Analyste développeur d'applications informatiques&quot; qui se déroule en 2 ans après un baccalauréat général, technologique ou professionnel et qui permet aux étudiants l'acquisition des bases en informatique, en conception assistée par ordinateur (ou &quot;C A O&quot;), en mécanique et en électronique, tout en se professionnalisant. Ces 2 formations sont certifiantes par un diplôme inscrit au Répertoire National de la Certification Professionnelle (ou &quot;RNCP&quot;), et sont donc reconnues par l’Etat. L'IMÉRIR dispose également d'une troisième formation, la &quot;Licence informatique spécialité robotique de prototypage&quot;, formation Bac +3 qui se déroule après l'obtention d'un diplôme ou d'un titre professionnel de niveau Bac +2. Cette formation couvre les principaux domaines de l'informatique (comme le développement, les réseaux ou encore l'architecture des machines) mais avec une spécialisation dans les domaines de la robotique. Point intéressant ! Il vous est possible de valider les formations &quot;Manager de systèmes informatique et robotique&quot; et &quot;Licence informatique spécialité robotique de prototypage&quot; en validation des acquis de l'experience (en abrégé &quot;V A E&quot;). Et ça, c'est cool comme Ra's al Ghul !</translation>
        </message>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Aujourd’hui, L’IMÉRIR dispense 3 formations dans les domaines de l’informatique et de la robotique. Sa principale est &quot;Manadgeure de systèmes informatique et robotique&quot; (en abrégé &quot;MSIR&quot;). C'est une formation Bac +5 qui se déroule en 3 ans après un brevet de technicien supérieur (ou &quot;BTS&quot;), un bachelor universitaire de technologie (ou &quot;B U T&quot;) ou une prépa scientifique et technique, qui est polyvalente car conjuguant l'acquisition des compétences en informatique, en robotique et en management pour permettre aux étudiants de diriger n’importe quel projet informatique et robotique dès l’obtention de leur diplôme. Pour tous ceux qui ne disposent pas du bagage requis: pas de panique ! L'IMÉRIR dispose d'une formation Bac +2, intitulée &quot;Analyste développeur d'applications informatiques&quot;, qui se déroule en 2 ans après un baccalauréat général, technologique ou professionnel et qui permet aux étudiants l'acquisition des bases en informatique, en conception assistée par ordinateur (ou &quot;Cé Ah Oh&quot;), en mécanique et en électronique, tout en se professionnalisant. Ces 2 formations sont certifiantes par un diplôme inscrit au Répertoire National de la Certification Professionnelle (ou &quot;RNCP&quot;), et sont donc reconnues par l’Etat. L'IMÉRIR dispose également d'une troisième formation, la &quot;Licence informatique spécialité robotique de prototypage&quot;, formation Bac +3 qui se déroule après l'obtention d'un diplôme ou d'un titre professionnel de niveau Bac +2. Cette formation couvre les principaux domaines de l'informatique (comme le développement, les réseaux ou encore l'architecture des machines) mais avec une spécialisation dans les domaines de la robotique. Point intéressant ! Il t'est possible de valider, les formations &quot;Manadgeure de systèmes informatique et robotique&quot;, et &quot;Licence informatique spécialité robotique de prototypage&quot;, en validation des acquis de l'experience (en abrégé &quot;V A E&quot;). Et ça, c'est cool comme Ra's al Ghoul !</source>
            <comment>Text</comment>
            <translation type="unfinished">Aujourd’hui, L’IMÉRIR dispense 3 formations dans les domaines de l’informatique et de la robotique. Sa principale est &quot;Manadgeure de systèmes informatique et robotique&quot; (en abrégé &quot;MSIR&quot;). C'est une formation Bac +5 qui se déroule en 3 ans après un brevet de technicien supérieur (ou &quot;BTS&quot;), un bachelor universitaire de technologie (ou &quot;B U T&quot;) ou une prépa scientifique et technique, qui est polyvalente car conjuguant l'acquisition des compétences en informatique, en robotique et en management pour permettre aux étudiants de diriger n’importe quel projet informatique et robotique dès l’obtention de leur diplôme. Pour tous ceux qui ne disposent pas du bagage requis: pas de panique ! L'IMÉRIR dispose d'une formation Bac +2, intitulée &quot;Analyste développeur d'applications informatiques&quot;, qui se déroule en 2 ans après un baccalauréat général, technologique ou professionnel et qui permet aux étudiants l'acquisition des bases en informatique, en conception assistée par ordinateur (ou &quot;Cé Ah Oh&quot;), en mécanique et en électronique, tout en se professionnalisant. Ces 2 formations sont certifiantes par un diplôme inscrit au Répertoire National de la Certification Professionnelle (ou &quot;RNCP&quot;), et sont donc reconnues par l’Etat. L'IMÉRIR dispose également d'une troisième formation, la &quot;Licence informatique spécialité robotique de prototypage&quot;, formation Bac +3 qui se déroule après l'obtention d'un diplôme ou d'un titre professionnel de niveau Bac +2. Cette formation couvre les principaux domaines de l'informatique (comme le développement, les réseaux ou encore l'architecture des machines) mais avec une spécialisation dans les domaines de la robotique. Point intéressant ! Il t'est possible de valider, les formations &quot;Manadgeure de systèmes informatique et robotique&quot;, et &quot;Licence informatique spécialité robotique de prototypage&quot;, en validation des acquis de l'experience (en abrégé &quot;V A E&quot;). Et ça, c'est cool comme Ra's al Ghoul !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Nous contacter</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Pour nous contacter, rien de plus simple. Tu peux nous téléphoner au 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux également nous envoyer un message depuis le site officiel de l'école dans le menu &quot;Contact&quot;, et nous n'hésiterons pas à te lire et à te répondre. Si tu es par contre très curieux, tu peux aussi venir nous voir directement dans nos locaux. Ils sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. Et voilà ! Maintenant, tu peux nous contacter quand tu veux.</source>
            <comment>Text</comment>
            <translation type="unfinished">Pour nous contacter, rien de plus simple. Tu peux nous téléphoner au 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux également nous envoyer un message depuis le site officiel de l'école dans le menu &quot;Contact&quot;, et nous n'hésiterons pas à te lire et à te répondre. Si tu es par contre très curieux, tu peux aussi venir nous voir directement dans nos locaux. Ils sont situés sur le Purple campus de Perpignan, au 1, Avenue Paul Pascot, 66000, Perpignan. Je répète, au 1, Avenue Paul Pascot, 66000, Perpignan. Et voilà ! Maintenant, tu peux nous contacter quand tu veux.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Numéro de téléphone</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Alors, le numéro de téléphone de l'IMÉRIR, est le 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux nous joindre le matin entre 8 heures 15 et 12 heures 30, puis l'après-midi entre 13 heures 30 et 17 heures 15, du lundi au vendredi. Tu as une question ? Mes collègues humains au téléphone, n'hésiteront pas, à te répondre.</source>
            <comment>Text</comment>
            <translation type="unfinished">Alors, le numéro de téléphone de l'IMÉRIR, est le 04 68 56 80 18. Je répète, le 04 68 56 80 18. Tu peux nous joindre le matin entre 8 heures 15 et 12 heures 30, puis l'après-midi entre 13 heures 30 et 17 heures 15, du lundi au vendredi. Tu as une question ? Mes collègues humains au téléphone, n'hésiteront pas, à te répondre.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Professionnels</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>En tant qu'école, résolument tournée vers la professionnalisation de ses étudiants, les cours dispensés à l'IMÉRIR, le sont par des professionnels. L'école comporte 4 professeurs permanents et une trentaine d'intervenants extérieurs. Les professeurs permanents, eux, sont des enseignants salariés de l'école. Et en tant que tel, ils organisent, également, les enseignements dispensés, dans les différentes formations, et le programme pédagogique de ces derniers. Les enseignements correspondants, coïncident avec les techniques et concepts, utilisés dans le monde de l'entreprise. Les intervenants extérieurs, en revanche, travaillent dans le monde de l’entreprise la majeure partie de leur temps, mais font partager leur savoir avec les étudiants de l'IMÉRIR, dans le domaine sur lequel ils sont professionnellement spécialisés, et bien sûr compétents. Malgré le fait qu'ils travaillent la majeure partie de leur temps en entreprise, les intervenants extérieurs sont, aussi disponibles, que les professeurs permanents. Alors ! Tu en conviendras qu'un grand pouvoir, implique de grandes responsabilités !</source>
            <comment>Text</comment>
            <translation type="unfinished">En tant qu'école, résolument tournée vers la professionnalisation de ses étudiants, les cours dispensés à l'IMÉRIR, le sont par des professionnels. L'école comporte 4 professeurs permanents et une trentaine d'intervenants extérieurs. Les professeurs permanents, eux, sont des enseignants salariés de l'école. Et en tant que tel, ils organisent, également, les enseignements dispensés, dans les différentes formations, et le programme pédagogique de ces derniers. Les enseignements correspondants, coïncident avec les techniques et concepts, utilisés dans le monde de l'entreprise. Les intervenants extérieurs, en revanche, travaillent dans le monde de l’entreprise la majeure partie de leur temps, mais font partager leur savoir avec les étudiants de l'IMÉRIR, dans le domaine sur lequel ils sont professionnellement spécialisés, et bien sûr compétents. Malgré le fait qu'ils travaillent la majeure partie de leur temps en entreprise, les intervenants extérieurs sont, aussi disponibles, que les professeurs permanents. Alors ! Tu en conviendras qu'un grand pouvoir, implique de grandes responsabilités !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Qui sommes nous ?</name>
        <message>
            <source>L’IMÉRIR est une école supérieure de la C C I, pour &quot;Chambre de commerce et d'industrie&quot;, des Pyrénées Orientales, fondée en 1981, et basée à Perpignan, plus exactement sur 'Purple campus'. L’IMÉRIR prépare aux métiers de la robotique, de l’informatique, des objets connectés, et de l'intelligence artificielle. Le management et la gestion de projets y sont également abordés. Notre école dispose aussi d'un fablab, un lieu où sont disponibles des imprimantes 3D, une découpeuse laser, des robots industriels, comme mes amis robots de chez Kouka, Fanuc, et Staubli, des fers à souder, du matériel électronique et tous ce qui est nécessaire, pour le développement de projets maikeur, et qui sont utiles pour réaliser des projets d'école, des projets personnels, voire des projets d'ordre professionnel. L’IMÉRIR cultive aussi des partenariats, comme avec le groupe école Pratique à Marseille, le centre de formation de la C C I Marseille-Provence.</source>
            <comment>Text</comment>
            <translation type="obsolete">L’IMÉRIR est une école supérieure de la C C I, pour &quot;Chambre de commerce et d'industrie&quot;, des Pyrénées Orientales, fondée en 1981, et basée à Perpignan, plus exactement sur 'Purple campus'. L’IMÉRIR prépare aux métiers de la robotique, de l’informatique, des objets connectés, et de l'intelligence artificielle. Le management et la gestion de projets y sont également abordés. Notre école dispose aussi d'un fablab, un lieu où sont disponibles des imprimantes 3D, une découpeuse laser, des robots industriels, comme mes amis robots de chez Kouka, Fanuc, et Staubli, des fers à souder, du matériel électronique et tous ce qui est nécessaire, pour le développement de projets maikeur, et qui sont utiles pour réaliser des projets d'école, des projets personnels, voire des projets d'ordre professionnel. L’IMÉRIR cultive aussi des partenariats, comme avec le groupe école Pratique à Marseille, le centre de formation de la C C I Marseille-Provence.</translation>
        </message>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>L’IMÉRIR est une école supérieure de la C C I, pour &quot;Chambre de commerce et d'industrie&quot;, des Pyrénées Orientales, fondée en 1981, et basée à Perpignan, plusse exactement sur 'Purple campus'. L’IMÉRIR prépare aux métiers de la robotique, de l’informatique, des objets connectés, et de l'intelligence artificielle. Le management et la gestion de projets y sont également abordés. Notre école dispose aussi d'un fablab, un lieu où sont disponibles des imprimantes 3D, une découpeuse laser, des robots industriels, comme mes amis robots de chez Kouka, Fanuc, et Staubli, des fers à souder, du matériel électronique et tous ce qui est nécessaire, pour le développement de projets maikeur, et qui sont utiles pour réaliser des projets d'école, des projets personnels, voire des projets d'ordre professionnel. L’IMÉRIR cultive aussi des partenariats, comme avec le groupe école Pratique à Marseille, le centre de formation de la C C I Marseille-Provence.</source>
            <comment>Text</comment>
            <translation type="unfinished">L’IMÉRIR est une école supérieure de la C C I, pour &quot;Chambre de commerce et d'industrie&quot;, des Pyrénées Orientales, fondée en 1981, et basée à Perpignan, plusse exactement sur 'Purple campus'. L’IMÉRIR prépare aux métiers de la robotique, de l’informatique, des objets connectés, et de l'intelligence artificielle. Le management et la gestion de projets y sont également abordés. Notre école dispose aussi d'un fablab, un lieu où sont disponibles des imprimantes 3D, une découpeuse laser, des robots industriels, comme mes amis robots de chez Kouka, Fanuc, et Staubli, des fers à souder, du matériel électronique et tous ce qui est nécessaire, pour le développement de projets maikeur, et qui sont utiles pour réaliser des projets d'école, des projets personnels, voire des projets d'ordre professionnel. L’IMÉRIR cultive aussi des partenariats, comme avec le groupe école Pratique à Marseille, le centre de formation de la C C I Marseille-Provence.</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Robotique d'innovation</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;robotique d'innovation&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Robotique d'innovation&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans la robotique industrielle, la robotique de service, les cobots, la conception robotique, le prototypage, ainsi que la culture maikeur, et les nouvelles bases d'innovation. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici la &quot;Robotique d'innovation&quot;. C'est simple comme bonjour !</source>
            <comment>Text</comment>
            <translation type="unfinished">Le diplôme &quot;Manadgeure de systèmes informatique et robotique&quot; (ou &quot;MSIR&quot;), option &quot;robotique d'innovation&quot;, est un diplôme Bac +5, et donc, de niveau &quot;ingénieur&quot;, qui te permet de recevoir une formation solide, et polyvalente, dans les domaines de l'informatique, de la robotique, des objets connectés, de l'intelligence artificielle, du réseau, de cybersécurité, du prototypage et du management de projet. Cette formation se prépare sur 3 ans, après l'obtention d'un diplôme scientifique Bac +2, au mimumum, comme un brevet de technicien supérieur (ou &quot;BTS&quot;), ou encore un bachelor universitaire de technologie (ou &quot;B U T&quot;). Comme toutes les autres formations, celle-ci s'effectue en alternance. Et donc, tu acquiers de nouveaux savoirs, et de nouvelles compétences en cours, avec une mise en pratique directe en entreprise en qualité de salarié. De plus, dès le premier semestre, de la troisième et dernière année de formation, tu peux partir à l’étranger, dans le cadre du programme Erasmus. Tu étudies alors, dans une université ou une école d’accueil, partenaire de l’IMÉRIR, tout en perfectionnant ton anglais, en découvrant de nouveaux pays, et de nouvelles cultures. De nouvelles relations, peuvent s'ouvrir aussi à toi. Quelle aventure ! L'option &quot;Robotique d'innovation&quot;, choisi dès le second semestre, de la seconde année de formation, te permettra de te spécialiser dans la robotique industrielle, la robotique de service, les cobots, la conception robotique, le prototypage, ainsi que la culture maikeur, et les nouvelles bases d'innovation. Wow ! Impressionnant ! Non ? Tu obtiens ton diplôme, en soutenant un mémoire de fin d'études devant un jury, en validant tes périodes en entreprise, et en obtenant la moyenne scolaire, dans toutes tes matières et ta spécialité, ici la &quot;Robotique d'innovation&quot;. C'est simple comme bonjour !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/S'inscrire</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Pour t'inscrire, c'est très facile. Il te suffit de remplir un dossier d'inscription, depuis le site officiel de l'IMÉRIR, dans le menu &quot;Admissions&quot;, puis le sous-menu &quot;Demander mon dossier&quot;. Tu renseignes alors, la formation que tu demandes, ton nom de famille, ton prénom, et ton adresse email. Ton dossier d'inscription, te sera alors envoyé par email, et tu dois alors l'imprimer. Tu peux aussi demander, à mes collègues humains, s'ils n'en ont pas à disposition. Il te suffit alors de le remplir, puis de nous le retourner, avec tous les documents demandés, par la Poste, à l'adresse suivante: IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Je répète, IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Une fois le dossier d'inscription reçu, l'école traite ta demande. Il faut que tu aies fait, des études scientifiques, et que tu aies bien réussi ta scolarité, pour que ton dossier soit accepté. S'il est accepté, l'IMÉRIR t'invite, pour passer une session d'admission, dans ses locaux. Ton esprit logique, ta maitrise de l'anglais, ta maitrise du français, et ta capacité de raisonnement, sont alors mis à rude épreuve. Finalement, ta motivation est évaluée, au cours d'un entretien individuel avec l'équipe pédagogique de l'école. Dans la journée, tu es ensuite, informé de la décision de l'IMÉRIR, de te laisser intégrer l'école comme étudiant, ou non. C'est donc tout simple !</source>
            <comment>Text</comment>
            <translation type="unfinished">Pour t'inscrire, c'est très facile. Il te suffit de remplir un dossier d'inscription, depuis le site officiel de l'IMÉRIR, dans le menu &quot;Admissions&quot;, puis le sous-menu &quot;Demander mon dossier&quot;. Tu renseignes alors, la formation que tu demandes, ton nom de famille, ton prénom, et ton adresse email. Ton dossier d'inscription, te sera alors envoyé par email, et tu dois alors l'imprimer. Tu peux aussi demander, à mes collègues humains, s'ils n'en ont pas à disposition. Il te suffit alors de le remplir, puis de nous le retourner, avec tous les documents demandés, par la Poste, à l'adresse suivante: IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Je répète, IMÉRIR, 1, Avenue Paul Pascot, boîte postale 90443, 66004, Perpignan CEDEX. Une fois le dossier d'inscription reçu, l'école traite ta demande. Il faut que tu aies fait, des études scientifiques, et que tu aies bien réussi ta scolarité, pour que ton dossier soit accepté. S'il est accepté, l'IMÉRIR t'invite, pour passer une session d'admission, dans ses locaux. Ton esprit logique, ta maitrise de l'anglais, ta maitrise du français, et ta capacité de raisonnement, sont alors mis à rude épreuve. Finalement, ta motivation est évaluée, au cours d'un entretien individuel avec l'équipe pédagogique de l'école. Dans la journée, tu es ensuite, informé de la décision de l'IMÉRIR, de te laisser intégrer l'école comme étudiant, ou non. C'est donc tout simple !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Say</name>
        <message>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="vanished">Bonjour</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/Sessions ARE (aide à la recherche d'entreprises)</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Sessions A R E ? Quésaco ? Acronyme de, &quot;Aide à la Recherche d'Entreprises&quot;, les sessions A R E sont des sessions collectives, pour l'accompagnement des étudiants, dans leur recherche d'une entreprise d'accueil, en tant qu'alternant. Au cours de cette session, durant 2 ou 3 jours, tu apprendras à bien rédiger un CV, et une lettre de motivation, à cibler les entreprises qui t'intéressent, à relancer celles qui ont déjà reçu une candidature de ta part, à organiser tes recherches d'une entreprise d'accueil, à te présenter, à vendre tes compétences, et à communiquer auprès d'un recruteur potentiel. Tu apprendras également, comment tirer profit du réseau des anciens étudiants de l'école, grâce à leur annuaire,pour décrocher ton contrat en alternance, dans ton entreprise d'accueil. Décidément, l'IMÉRIR c'est comme Skip ! Petit, mais puissant !</source>
            <comment>Text</comment>
            <translation type="unfinished">Sessions A R E ? Quésaco ? Acronyme de, &quot;Aide à la Recherche d'Entreprises&quot;, les sessions A R E sont des sessions collectives, pour l'accompagnement des étudiants, dans leur recherche d'une entreprise d'accueil, en tant qu'alternant. Au cours de cette session, durant 2 ou 3 jours, tu apprendras à bien rédiger un CV, et une lettre de motivation, à cibler les entreprises qui t'intéressent, à relancer celles qui ont déjà reçu une candidature de ta part, à organiser tes recherches d'une entreprise d'accueil, à te présenter, à vendre tes compétences, et à communiquer auprès d'un recruteur potentiel. Tu apprendras également, comment tirer profit du réseau des anciens étudiants de l'école, grâce à leur annuaire,pour décrocher ton contrat en alternance, dans ton entreprise d'accueil. Décidément, l'IMÉRIR c'est comme Skip ! Petit, mais puissant !</translation>
        </message>
    </context>
    <context>
        <name>behavior_1/behavior.xar:/prepa</name>
        <message>
            <location filename="behavior_1/behavior.xar" line="0"/>
            <source>Bonjour</source>
            <comment>Text</comment>
            <translation type="unfinished">Bonjour</translation>
        </message>
    </context>
</TS>
